### ISSUE TITLE
An error occurred when cloning the repository

### ISSUE THREAD

**Issue by DeeJay1221** [qiyu3816/MTFNN-CO#1]
When I cloned the repository, the error message I encountered was as follows:
“Error downloading object: datasets/2nodes_40000samples.csv (f35ae8b): Smudge error: Error downloading datasets/2nodes_40000samples.csv (f35ae8b975dade23586a2037ab3b40eee72b8a81cea3123dc5ddf90d5db400ea): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.”

**Comment by qiyu3816** [comment]
Sorry for that problem, we've exceeded the Large File Storage (LFS) quota of this repository and there are no plans to upgrade the quota in the short term. But **you should still be able to clone the repository and access the non-LFS files without any issues**. The files linked to LFS in this repository are all dataset files, so if you need them, we will send to you via issue email response later.

**Comment by qiyu3816** [comment]
We apologize for the caused&nbsp;inconvenience.&nbsp;

The files linked to LFS in qiyu3816/MTFNN-CO are sent in attachments.


Imladris
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qiyu3816/MTFNN-CO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月13日(星期五) 晚上8:01
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qiyu3816/MTFNN-CO] An error occurred when cloning the repository (Issue #1)





 
When I cloned the repository, the error message I encountered was as follows:
 “Error downloading object: datasets/2nodes_40000samples.csv (f35ae8b): Smudge error: Error downloading datasets/2nodes_40000samples.csv (f35ae8b975dade23586a2037ab3b40eee72b8a81cea3123dc5ddf90d5db400ea): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.”
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

lfs_files.rar (170.40M, 2023年11月13日 09:34 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=23353035dfec6ac6399326604361011c19415302575206524c570907014c040153041d570303021e505751045d520755530d0803656c335f07466f530c0d56404f475147655c&code=a505ea33

**Comment by qiyu3816** [comment]
The files linked to LFS in this repository have been sent as email attachments. If there are no problems, this issue will be closed before the end of today.

**Comment by DeeJay1221** [comment]
Your prompt response and solution were greatly appreciated and I'm grateful for your assistance! 
Wishing you all the best!
