### ISSUE TITLE
An error occurred when cloning the repository

### ISSUE THREAD

**Issue by liujiangying** [qiyu3816/MTFNN-CO#2]
Hello, I'm also experiencing this issue. When I cloned the repository, the error message I encountered was as follows:
“Error downloading object: datasets/2nodes_40000samples.csv (f35ae8b): Smudge error: Error downloading datasets/2nodes_40000samples.csv (f35ae8b975dade23586a2037ab3b40eee72b8a81cea3123dc5ddf90d5db400ea): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.”
Would you like to send a copy to my e-mail?Sorry for your help!

**Comment by qiyu3816** [comment]
We apologize for the caused inconvenience.
The files linked to LFS in qiyu3816/MTFNN-CO are sent in attachments.





Imladris
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qiyu3816/MTFNN-CO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月4日(星期一) 中午11:49
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qiyu3816/MTFNN-CO] An error occurred when cloning the repository (Issue #2)





 
Hello, I'm also experiencing this issue. When I cloned the repository, the error message I encountered was as follows:
 “Error downloading object: datasets/2nodes_40000samples.csv (f35ae8b): Smudge error: Error downloading datasets/2nodes_40000samples.csv (f35ae8b975dade23586a2037ab3b40eee72b8a81cea3123dc5ddf90d5db400ea): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.”
 Would you like to send a copy to my e-mail?Sorry for your help!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

lfs_files.rar (170.40M, 2024年01月03日 16:22 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=7636346179be69966c9022344330024c4c4252555051525019545055031d0156560519025601024e005450575502555401530756653d300f52456b070c5c55101a445513650d&t=exs_ftn_download&code=464ae00c

**Comment by liujiangying** [comment]
Thank you very much for your prompt reply and solution, thank you!
