### ISSUE TITLE
An error occurred when cloning the repository 

### ISSUE THREAD

**Issue by Howdy1218** [qiyu3816/MTFNN-CO#4]
I meet the same mistake:" When I cloned the repository, the error message I encountered was as follows:
“Error downloading object: datasets/2nodes_40000samples.csv (f35ae8b): Smudge error: Error downloading datasets/2nodes_40000samples.csv (f35ae8b975dade23586a2037ab3b40eee72b8a81cea3123dc5ddf90d5db400ea): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.”", too. Could you please send the email to me? We look forward to hearing from you, thanks a lot!

**Comment by qiyu3816** [comment]
We are very sorry for the trouble!&nbsp;


We send all the datasets by email attachment.&nbsp;


Thanks for understanding!




Imladris
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qiyu3816/MTFNN-CO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月12日(星期天) 晚上6:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qiyu3816/MTFNN-CO] the same mistake (Issue #4)





 
I meet the same mistake:" When I cloned the repository, the error message I encountered was as follows:
 “Error downloading object: datasets/2nodes_40000samples.csv (f35ae8b): Smudge error: Error downloading datasets/2nodes_40000samples.csv (f35ae8b975dade23586a2037ab3b40eee72b8a81cea3123dc5ddf90d5db400ea): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.”", too. Could you please send the email to me? We look forward to hearing from you, thanks a lot!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

datasets.rar (160.74M, 2024年06月11日 18:24 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=233339399807c4963a952f6c1737024c1a475c5a005652074f040908531a07025200140b0002004e50060e090705555253565d0e313b30070347584a5443434d10524b390c&t=exs_ftn_download&code=b399170c

**Comment by Howdy1218** [comment]
Thank you very much for your help. I apologize for not expressing my gratitude in a timely manner. I believe your reply will bring me a lot of benefits
